---
    - name: Does the Google apt file exist?
      command: test -f /etc/apt/sources.list.d/google-chrome.list
      register: google_apt_exists
      ignore_errors: true

    - name: Download chrome-stable
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        dest: /tmp/google-chrome-stable_current_amd64.deb
      when: google_apt_exists.rc == 1

    - name: Install chrome-stable
      shell: sudo yum localinstall google-chrome-stable_current_x86_64.rpm
      when: google_apt_exists.rc == 1